spring:
  datasource:
    url: jdbc:h2:mem:db_test;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
custom:
  temp:
    dirPath: c:/temp/auth_2024_test/temp
  genFile:
    dirPath: c:/temp/auth_2024_test